config/routes.rb
Mvcex::Application.routes.draw do

  devise_for :authors

  root :to => "application#index"

  resources :authors
  
  resources :articles do
    collection do
      get :list
    end
    resources :comments
  end
  
  
  
  

  
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author,  :foreign_key =>"author_id"
  has_many :comments, :dependent => :destroy
  
  VALID = ["draft", "posted"]
   
  order_me "title"
  validates_presence_of :title, :body
  validates_inclusion_of :status, :in => VALID
  before_save :set_date_posted
  
  scope :drafts, where(["status = ?", VALID[0]])
  scope :posted, where(["status = ?", VALID[1]])
  
  def set_date_posted
    self.date_posted = self.status.downcase == "posted" ? Time.now : nil
  end
  
  def posted?
    self.status == VALID[1] ? true : false; 
  end
  
end

# == Schema Information
#
# Table name: articles
#
#  id          :integer(4)      not null, primary key
#  title       :string(255)
#  body        :text
#  status      :text
#  date_posted :datetime
#  author_id   :integer(4)
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :get_authors

  def index
    #@articles = Article.all
    #@drafts = Article.drafts
    @posted = Article.posted.paginate :page => params[:page], :per_page => 5
    respond_to do |format|
      format.html
      format.xml
    end 
  end

  def show
    @article = Article.find params[:id]
    @author = Author.find @article.author_id
    #@comments = @article.comments.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 5
    @comments = @article.comments
    respond_to { |format| format.html }
  end

  def new
    @article = Article.new
    
    respond_to do |format|
      format.html

    end
  end

  def edit
    @article = Article.find params[:id]
  end

  def create
    @article= current_author.articles.build(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully published.') }
      else
        format.html { render :action => "new" }
        flash[:error] = "Wrong again"
      end
    end
  end
  
  def update
    @article = Article.find(params[:id])
    
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully published.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
    end
  end
  
  def list
    @articles = current_author.articles.paginate :page => params[:page], :per_page => 5
  end
  
  def get_authors
    @authors = Author.all
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  def options_for_status
    options_for_select([["Draft", "draft"], ["Posted", "posted"]])
  end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ol>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ol>
    </div>
  <% end %>
  <% if flash[:error] %>
  <div id="flash"><%= flash[:error] %></div>
  <% end %>
 <ul id="form"> 

    <li><%= f.label :title %>
        <%= f.text_field :title %></li>
  
 
    <li><%= f.label :body %>
        <%= f.cktext_area :body, :toolbar=>'Full', :width=>'98%', :height=>'400px' %>
</li>
  
  
  
    <li><%= f.label :status %>
        <%= f.select :status, options_for_status  %></li>
 
  
  
    <li><%= f.submit %></li>
  </ul>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit <%= @article.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%if @authors.empty? %>
  <%= render :partial => 'authors/noauthors' %>
<% else %>
 <%= link_to 'Write a new article', new_article_path,  :class => "links" if author_signed_in? %>
  <% if @posted.empty? %>
    <p>There are no articles yet.</p>
  <% else %>
  <div id="search-form">
 <% form_tag do  %>
  <%= text_field_tag "article_name" %> 
 <% end %>
  </div>
  <div class="clear"></div>
  <ul id="main-list">
    <% @posted.each do |article|
          curclass = "" 
          curclass = article.author.eql?(current_author) ? "current-author" : "" %>
   <li><%= link_to article.title, article, :class => curclass %></li>
   <% end %>
  </ul>
  <%= will_paginate @posted %>

  <div class="page-entry-info"><%= page_entries_info @posted %></div>
  <% end %>
<% end %>

app/views/articles/index.html.haml
%h1 Articles
- if @authors.empty?
%p There are no authors yet. Please 
= link_to 'add one', new_author_path
- else
- if @articles.empty?
%p There are no articles yet
- else
%ul#main-list
@articles.each do |article|
= link_to article.title, article
= link_to 'Add new article', new_article_path if author_signed_in?

app/views/articles/list.html.erb
<h1>My Articles</h1>

 <%= link_to 'Write a new article', new_article_path,  :class => "links" if author_signed_in? %>
  <% if @articles.empty? %>
    <p>You have not yet written any articles.</p>
  <% else %>
  <ul id="main-list">
    <% @articles.each do |article| %>
      <% klass = "" 
       klass = article.posted? ? "posted" : "draft" %>
  
   <li><%= link_to article.title, article, :class => klass %></li>
   <% end %>
  </ul>
  <%= will_paginate @articles %>

  <div class="page-entry-info"><%= page_entries_info @articles %></div>
  <% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title%></h1>

<p>
  <ul id="article-info">
  <li><span>Author:</span> <%= link_to @author.full_name, author_path(@author) %></li>
  <li class="full-date"><%= "Date Posted: #{@article.date_posted}" if not @article.date_posted.nil? %></li>
  <li><span>Summary:</span> <div id="article-body"><%= @article.body.html_safe %></div></li>
  
 
  </ul>
  <% if current_author.eql? @author %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Delete', @article, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
   
  
</p>



<%if not @comments.empty? %>
<br/>
<h3>Comments</h3> 
<%= link_to 'Add a comment', "#comment-form", :id => "add-comment", :class => 'links' if author_signed_in? %>
<br/>
<div class="comment-list">
  <%= render :partial => 'comments/list'%>   
</div>
<% else %>
<div class="comment-list">
  <% if author_signed_in? %>
  <p>No comments yet. Be the first to <%= link_to 'add a comment', "#comment-form", :id => "add-comment"%></p>
  <% end %>
</div>
<% end %>

<% if not author_signed_in? %>
  Please <%= link_to 'log in', new_author_session_path, :remote => true %> to post a comment. Not yet a member? Sign up <%= link_to 'here', new_author_path %>!
  
<% else %>
<%= render :partial => 'comments/newform' %>   
<% end %>
 