config/routes.rb
Mvcex::Application.routes.draw do

  devise_for :authors

  root :to => "application#index"

  resources :authors
  
  resources :articles do
    collection do
      get :list
    end
    resources :comments
  end
  
  
  
  

  
  
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #custom gems
  geo_mappable 
  order_me "last_name"
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :photo, :birthday, :remarks, :place_attributes
  has_many :articles, :dependent => :destroy
  has_many :comments
  has_attached_file :photo, :styles => { :thumb=> "30x30>", :small  => "250x250>" }, :default_url => 'missing_:style.jpg'
  validates_presence_of :first_name, :last_name
  
  
  
  def full_name
    "#{last_name}, #{first_name}"
  end
  
end

# == Schema Information
#
# Table name: authors
#
#  id                     :integer(4)      not null, primary key
#  first_name             :string(255)
#  last_name              :string(255)
#  remarks                :text
#  birthday               :date
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  password_salt          :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  failed_attempts        :integer(4)      default(0)
#  unlock_token           :string(255)
#  locked_at              :datetime
#  authentication_token   :string(255)
#  photo_file_name        :string(255)
#  photo_content_type     :string(255)
#  photo_file_size        :integer(4)
#  photo_updated_at       :datetime
#

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :authenticate_author!, :except => [:index, :show, :new]

  def index
    @authors = Author.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 5
    
    respond_to do |format|
      format.html
     end
  end

  def show
    @author = Author.find params[:id]
    
    respond_to do |format|
      format.html
    end
  end

  def new
    @author = Author.new
    @author.build_place
    respond_to do |format|
      format.html
    end
  end

  def edit
    @author = Author.find params[:id]
    @author.build_place if @author.place.nil?
  end

  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to(@author, :notice => 'Author was successfully added.') }
      else
        format.html { render :action => "new" }
        flash[:error] = "Wrong again"
      end
    end
  end
  
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to(@author, :notice => 'Author was successfully added.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to(destroy_author_session_path) }
    end
  end
  
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> were encountered:</h2>

      <ol>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ol>
    </div>
  <% end %>
  <% if flash[:error] %>
  <div id="flash"><%= flash[:error] %></div>
  <% end %>
  <ul id="form">
    <li><%= f.label :first_name %>
          <%= f.text_field :first_name%></li>

    <li><%= f.label :last_name %>
        <%= f.text_field :last_name %></li>


    <li><%= f.label :remarks %>
        <%= f.text_area :remarks %></li>


    <li><%= f.label :birthday %>
        <%= f.text_field :birthday, :readonly => "readonly" %></li>
        
    <li>
      <%= f.fields_for :place do |place| %>
      <%= place.label :location %>
      <%= place.text_field :location %>
     <% end %>
    </li>


    <li><%= f.submit %></li>
  </ul>
<% end %>

app/views/authors/_noauthors.html.erb
<p>There are no authors yet. Be the first to <%= link_to "sign up!", new_author_path%></p>

app/views/authors/edit.html.erb
<h1>Edit <%= @author.full_name %></h1>

<%= render 'form' %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<%if @authors.empty? %>
  <%= render :partial => 'noauthors' %>
<% else %>
<ul id="main-list">
<% @authors.each do |author| %>
  <% curclass = "" 
     curclass = author.eql?(current_author) ? "current-author" : "" %>
  <li><%= image_tag author.photo.url(:thumb), :class => "photo-thumb" %> <%= link_to author.full_name, author, :class => curclass %></li>
<% end %>
</ul>
<%= will_paginate @authors %>

<div class="page-entry-info"><%= page_entries_info @authors %></div>
<% end %>

app/views/authors/new.html.erb
<h1>Sign up</h1>

<%= form_for(@author, :url => registration_path(@author), :html => { :multipart => true }) do |f| %>
<% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> were encountered:</h2>

      <ol>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ol>
    </div>
  <% end %>
<ul id="form">
  <li><%= f.label :email %>
      <%= f.email_field :email %></li>

  <li><%= f.label :password %>
      <%= f.password_field :password %></li>

  <li><%= f.label "Confirm Password" %>
      <%= f.password_field :password_confirmation %></li>
  
  <li><%= f.label :first_name %>
        <%= f.text_field :first_name%></li>

  <li><%= f.label :last_name %>
        <%= f.text_field :last_name %></li>

  <li><%= f.label :remarks %>
        <%= f.text_area :remarks %></li>

  <li>
    <%= f.fields_for :place do |places| %>
      <%= places.label :location %>
      <%= places.text_field :location %>
     <% end %>
  </li> 
  
  <li><%= f.label :birthday %>
        <%= f.text_field :birthday, :readonly => 'readonly' %></li>
        
  <li><%= f.label :photo %>
      <%= f.file_field :photo%></li>  

  <li><%= f.submit "Sign up" %></li>
   
</ul>

<% end %>

app/views/authors/show.html.erb
<h1><%= @author.full_name %></h1>
<div class="grid_3">
<%= image_tag @author.photo.url(:small), :class => "photo-small"%>
 <% if current_author.eql? @author %>
 <ul>
  <li><%= link_to 'Edit Profile', edit_author_path(@author), :class => "links" %></li>
  <li><%= link_to 'Write Article', new_article_path, :class => "links" %></li>
  <li><%= link_to 'Delete Profile', @author, :confirm => 'Are you sure?', :method => :delete, :class => "links" %></li>
</ul>
<% end %>
</div>
<div class="grid_5">
<ul  id="author-info">
  <%if @author.remarks != "" %>
  <li><span>I am:</span>
    <p>
      <%= @author.remarks %>
    </p> 
  </li>
  <%end%>
  <%if not @author.birthday.nil? %>
  <li><span>I was born on:</span> <%= @author.birthday %></li>
  <% end %>
  <li>
  <%if not @author.email.nil? %>
  <li><span>Contact me at:</span> <%= mail_to @author.email, @author.email %></li>
  <% end %>
  <li>
  
  <% if not @author.articles.posted.empty? %>
  <span>I have written:</span>
  <ul>
    <% @author.articles.posted.each do |a|%>
      <li><%= link_to a.title, article_path(a) %></li>
    <% end %>
  </ul>
  <% else %>
    I have not yet written any articles.
  <% end %></li>

<% if not @author.place.nil? %>
<li><span>You can find me at:</span>
    <div id="map_canvas"></div>
</li>
</ul>
</div>


<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true", 'gmap' %>
<script type="text/javascript">
  initialize(<%= @author.place.latitude %>, <%= @author.place.longitude%>, "<%= @author.place.location %>")
</script>
<% end %>