config/routes.rb
Mvcex::Application.routes.draw do

  devise_for :authors

  root :to => "application#index"

  resources :authors
  
  resources :articles do
    collection do
      get :list
    end
    resources :comments
  end
  
  
  
  

  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_author!, :except => [:index, :show]
  
  def index
    #raise 'error'
    @titulos = "Welcome!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<% if not author_signed_in? %>
<h1 id="welcome">Welcome!</h1>


<blockquote id="quote">"Writing is only boring to the people who are boring themselves." – Unknown</blockquote>
<div id="index-page">
<p>
Want to write? Why not? In the spirit of Lorem Ipsum Dolores... 

</p>

<%= form_for("author", :url => author_session_path) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in' %><br/>
  <%= link_to "Forgot your password?", new_password_path('author') %>
<% end %>
Do you want to be an author? Then <%= link_to 'sign up now!', new_author_path %>
</div>
<% else %>
<h1 id="welcome">Welcome <%= current_author.first_name%>!</h1>
<p>What do you want to do?</p>
<ul>
  <li><%= link_to "View my Profile",  author_path(current_author.id), :class => 'links' %></li>
  <li><%= link_to "Edit Profile",  edit_author_path(current_author.id), :class => 'links' %></li>
  <li><%= link_to "Write an Article",  new_article_path, :class => 'links' %></li>
  <li><%= link_to "View my Articles",  list_articles_path, :class => 'links' %></li>
  <li><%= link_to "Stalk other Authors",  authors_path, :class => 'links' %></li>
  <li><%= link_to "Read more Articles",  articles_path, :class => 'links' %></li>
</ul>
<% end %>